// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZuW-YULf_0GnScu-Mxk73VkjC0XwE0yA',
    appId: '1:19831531834:web:9c66d6ef9b523659c38803',
    messagingSenderId: '19831531834',
    projectId: 'newfirebase-c0711',
    authDomain: 'newfirebase-c0711.firebaseapp.com',
    storageBucket: 'newfirebase-c0711.appspot.com',
    measurementId: 'G-YSWP1Z6NBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBClyk_0pYAIaTbD0pjSM41ZM0Q-08pMw4',
    appId: '1:19831531834:android:2fedf64d47b2f0d8c38803',
    messagingSenderId: '19831531834',
    projectId: 'newfirebase-c0711',
    storageBucket: 'newfirebase-c0711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBWQ-Ti9DWgUPmHQWPXs_kdI5MDtsDKE4',
    appId: '1:19831531834:ios:9fa6a9ca7ba4532fc38803',
    messagingSenderId: '19831531834',
    projectId: 'newfirebase-c0711',
    storageBucket: 'newfirebase-c0711.appspot.com',
    iosBundleId: 'com.example.newfirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBWQ-Ti9DWgUPmHQWPXs_kdI5MDtsDKE4',
    appId: '1:19831531834:ios:d69329f3e42b99c3c38803',
    messagingSenderId: '19831531834',
    projectId: 'newfirebase-c0711',
    storageBucket: 'newfirebase-c0711.appspot.com',
    iosBundleId: 'com.example.newfirebaseProject.RunnerTests',
  );
}
